version: '3.8'


services:
  gaze_module:
    build:
      context: .
      dockerfile: Dockerfile.pupil-dev
      args:
          USER_ID: ${UID:-1000}
          GROUP_ID: ${GID:-1000}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - ./app/pupil_capture_settings:/app/pupil/capture_settings
    devices:
      - /dev/video0:/dev/video0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: host
    privileged: true
    group_add:
      - plugdev
    command: "python main.py capture" # --hide-ui"

  surface_module:
    build:
      context: .
      dockerfile: Dockerfile.opencv
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: host
    command: "python3 scripts/main.py"

    # Utility scripts
    # command: "python3 scripts/utility/tag_to_svg.py /app/tags/tag41_12_00003.png /app/tags/tag41_12_00003.svg --size=200mm"